{
 "title": "Unraid NUT UPS Dashboard TR",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "kwhprice", "label": "kWh Price", "query": "1.44" },
   { "name": "currency", "label": "Currency", "query": "₴,$,€,£,C$,kr,¥" },
   { "name": "upsdatasource", "label": "UPS Datasource", "query": "influxdb" },
   {
    "name": "RealPowerRating",
    "label": "RealPowerRating",
    "query": "SELECT \"value\" FROM \"modbus_value\" WHERE \"type_instance\" = 'ups_Output.RealPowerRating'"
   }
  ]
 },
 "panels": [
  {
   "title": "Input/Output, Energy, Load V, Wh, W",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "input_voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modbus_value",
     "query": "SELECT mean(\"value\") FROM \"modbus_value\" WHERE (\"type_instance\" = 'ups_InputVoltage') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "ups_InputVoltage" }
     ]
    },
    {
     "alias": "output_voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modbus_value",
     "query": "SELECT mean(\"value\") FROM \"modbus_value\" WHERE (\"type_instance\" = 'ups_InputVoltage') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "ups_Output[0].VoltageAC" }
     ]
    },
    {
     "alias": "Watt",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modbus_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " *10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "ups_RealLoadW" }
     ]
    },
    {
     "alias": "Watthours12h",
     "groupBy": [
      { "params": [ "23h59m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modbus_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "ups_Output.Energy" }
     ]
    }
   ]
  },
  {
   "title": "UPS Battery Charge",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Percent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "modbus_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "ups_StateOfCharge_Pct" }
     ]
    },
    {
     "alias": "Voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "modbus_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "ups_Battery.Positive.VoltageDC" }
     ]
    },
    {
     "alias": "Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "modbus_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "ups_BattTemp" }
     ]
    }
   ]
  },
  {
   "title": "Runtime left",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "time_remain",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modbus_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "ups_RuntimeLeft" }
     ]
    }
   ]
  },
  {
   "title": "Today's Usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modbus_value",
     "query": "SELECT sum(\"LOADPCT\") / 100 * 865 FROM \"APC\" WHERE \"LOADPCT\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "ups_Output.Energy" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 14, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"value\"::integer) & 2 FROM \"modbus_value\" WHERE (\"type_instance\" = 'ups_UPSStatus_BF') AND $timeFilter GROUP BY time($__interval) fill(null)\n"
    },
    {
     "query": "SELECT last(\"value\"::integer) & 4 FROM \"modbus_value\" WHERE (\"type_instance\" = 'ups_UPSStatus_BF') AND $timeFilter GROUP BY time($__interval) fill(null)\n"
    },
    {
     "query": "SELECT last(\"value\"::integer) & 8 FROM \"modbus_value\" WHERE (\"type_instance\" = 'ups_UPSStatus_BF') AND $timeFilter GROUP BY time($__interval) fill(null)\n"
    },
    {
     "query": "SELECT last(\"value\"::integer) & 64 FROM \"modbus_value\" WHERE (\"type_instance\" = 'ups_UPSStatus_BF') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "query": "SELECT last(\"value\"::integer) & 8192 FROM \"modbus_value\" WHERE (\"type_instance\" = 'ups_UPSStatus_BF') AND $timeFilter GROUP BY time($__interval) fill(null)\n"
    }
   ]
  },
  {
   "title": "Today's Cost",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Costs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "modbus_value",
     "query": "SELECT difference(mean(\"value\")) /1000*$kwhprice FROM \"modbus_value\" WHERE (\"type_instance\" = 'ups_Output.Energy') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "/1000*$kwhprice" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "ups_Output.Energy" }
     ]
    }
   ]
  },
  {
   "title": "Current UPS Load",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Watts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "modbus_value",
     "query": "SELECT sum(\"LOADPCT\") / 100 * 865 FROM \"APC\" WHERE \"LOADPCT\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*$RealPowerRating/100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "ups_RealLoadW" }
     ]
    }
   ]
  },
  {
   "title": "Average UPS Load",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 17, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Watts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "modbus_value",
     "query": "SELECT sum(\"LOADPCT\") / 100 * 865 FROM \"APC\" WHERE \"LOADPCT\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*$RealPowerRating/100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "ups_RealLoadW" }
     ]
    }
   ]
  },
  {
   "title": "This Week's Usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modbus_value",
     "query": "SELECT sum(\"LOADPCT\") / 100 * 865 FROM \"APC\" WHERE \"LOADPCT\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "ups_Output.Energy" }
     ]
    }
   ]
  },
  {
   "title": "Time on BAT/LINE",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upsd",
     "query": "SELECT INTEGRAL(on_battery) AS \"BATTERY\" FROM (SELECT FLOOR(1/(\"value\"+1)) AS on_battery FROM \"modbus_value\"  WHERE  (\"type_instance\" = 'ups_InputVoltage') AND $timeFilter)\n\n",
     "select": [
      [
       { "params": [ "input_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "query": "SELECT INTEGRAL(on_line) AS \"ONLINE\" FROM (SELECT 1-(FLOOR(1/(value+1))) AS on_line FROM \"modbus_value\"  WHERE (\"type_instance\" = 'ups_InputVoltage') AND $timeFilter)"
    }
   ]
  },
  {
   "title": "This Week's Cost",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "modbus_value",
     "query": "SELECT sum(\"LOADPCT\") / 100 * 865 FROM \"APC\" WHERE \"LOADPCT\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "/1000*$kwhprice" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "ups_Output.Energy" }
     ]
    }
   ]
  },
  {
   "title": "This Month's Usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Wh",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "modbus_value",
     "query": "SELECT sum(\"LOADPCT\") / 100 * 865 FROM \"APC\" WHERE \"LOADPCT\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "ups_Output.Energy" }
     ]
    }
   ]
  },
  {
   "title": "Battery Data",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "bat_percent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modbus_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "ups_StateOfCharge_Pct" }
     ]
    },
    {
     "alias": "bat_temp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modbus_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "ups_BattTemp" }
     ]
    },
    {
     "alias": "bat_volt_pos",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modbus_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "ups_Battery.Positive.VoltageDC" }
     ]
    },
    {
     "alias": "load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modbus_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "ups_RealLoadW" }
     ]
    }
   ]
  },
  {
   "title": "This Month's Cost",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "modbus_value",
     "query": "SELECT sum(\"LOADPCT\") / 100 * 865 FROM \"APC\" WHERE \"LOADPCT\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "/1000*$kwhprice" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "ups_Output.Energy" }
     ]
    }
   ]
  },
  {
   "title": "This Year's Usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "kWh",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modbus_value",
     "query": "SELECT sum(\"LOADPCT\") / 100 * 865 FROM \"APC\" WHERE \"LOADPCT\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "ups_Output.Energy" }
     ]
    }
   ]
  },
  {
   "title": "This Year's Cost",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "modbus_value",
     "query": "SELECT sum(\"LOADPCT\") / 100 * 865 FROM \"APC\" WHERE \"LOADPCT\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "/1000/180*$kwhprice" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "ups_Output.Energy" }
     ]
    }
   ]
  },
  {
   "title": "Estimated Yearly Usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Costs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ups_status",
     "query": "SELECT sum(\"LOADPCT\") / 100 * 865 FROM \"APC\" WHERE \"LOADPCT\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "watts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/1000*24*365" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Estimated Yearly Cost",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Costs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ups_status",
     "query": "SELECT sum(\"LOADPCT\") / 100 * 865 FROM \"APC\" WHERE \"LOADPCT\" = 'loadpercent' AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "watts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/1000*24*$kwhprice*365" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "This Month Consumption/Costs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "Wh",
     "query": "SELECT difference(last(\"value\")) FROM \"modbus_value\" WHERE (\"type_instance\" = 'ups_Output.Energy') AND $timeFilter GROUP BY time($interval) fill(null)\n"
    },
    {
     "alias": "Hrivna",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modbus_value",
     "query": "SELECT difference(last(\"value\"))*$kwhprice/1000 FROM \"modbus_value\" WHERE (\"type_instance\" = 'ups_Output.Energy') AND $timeFilter GROUP BY time($interval) fill(null)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ " /1000*$kwhprice" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "ups_Output.Energy" }
     ]
    }
   ]
  },
  {
   "title": "This Week Consumption/Costs_PASHA",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "Wh",
     "query": "SELECT difference(last(\"value\")) FROM \"modbus_value\" WHERE (\"type_instance\" = 'ups_Output.Energy') AND $timeFilter GROUP BY time($interval) fill(null)\n"
    },
    {
     "alias": "Hrivna",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modbus_value",
     "query": "SELECT difference(last(\"value\"))*$kwhprice/1000 FROM \"modbus_value\" WHERE (\"type_instance\" = 'ups_Output.Energy') AND $timeFilter GROUP BY time($interval) fill(null)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ " /1000*$kwhprice" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "ups_Output.Energy" }
     ]
    }
   ]
  },
  {
   "title": "Status_PASHA",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "query": "SELECT FLOOR((last(\"value\"::integer) & 4)/4) AS on_BAT FROM \"modbus_value\" WHERE (\"type_instance\" = 'ups_UPSStatus_BF') AND $timeFilter GROUP BY time($__interval) fill(null)\n"
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modbus_value",
     "query": "SELECT FLOOR((last(\"value\"::integer) & 2)/2) AS on_LINE FROM \"modbus_value\" WHERE (\"type_instance\" = 'ups_UPSStatus_BF') AND $timeFilter GROUP BY time($__interval) fill(null)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "ups_UPSStatus_BF" }
     ]
    },
    {
     "query": "SELECT FLOOR((last(\"value\"::integer) & 8192)/8192) AS GreenMode FROM \"modbus_value\" WHERE (\"type_instance\" = 'ups_UPSStatus_BF') AND $timeFilter GROUP BY time($__interval) fill(null)\n"
    },
    {
     "query": "SELECT FLOOR((last(\"value\"::integer) & 256)/256) AS StateOutputOff FROM \"modbus_value\" WHERE (\"type_instance\" = 'ups_UPSStatus_BF') AND $timeFilter GROUP BY time($__interval) fill(null)\n"
    },
    {
     "query": "SELECT FLOOR((last(\"value\"::integer) & 16384)/16384) AS Test_Modifier FROM \"modbus_value\" WHERE (\"type_instance\" = 'ups_UPSStatus_BF') AND $timeFilter GROUP BY time($__interval) fill(null)\n"
    }
   ]
  },
  {
   "title": "UPS Load, W",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "watt", "label": "Percent" }
   ],
   "targets": [
    {
     "alias": "UPS Load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "modbus_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " *10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "ups_RealLoadW" }
     ]
    }
   ]
  },
  {
   "title": "This Week Consumption/Costs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "watt", "label": "Load" }
   ],
   "targets": [
    {
     "alias": "Wh",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modbus_value",
     "query": "SELECT sum(\"value\") FROM \"power\" WHERE \"host\" = 'mainpower' AND $timeFilter GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "ups_Output.Energy" }
     ]
    }
   ]
  },
  {
   "title": "This Month Consumption/Costs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 11, "y": 40 },
   "yaxes": [
    { "format": "kwatth", "label": "Load" }
   ],
   "targets": [
    {
     "alias": "Costs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upsd",
     "query": "SELECT sum(\"value\") *0.22/1000 FROM \"power\" WHERE \"host\" = 'mainpower' AND $timeFilter GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "*900/100/1000/180*$kwhprice" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "kWh",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "upsd",
     "query": "SELECT sum(\"value\") FROM \"power\" WHERE \"host\" = 'mainpower' AND $timeFilter GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "*900/100/1000/180" ], "type": "math" }
      ]
     ]
    }
   ]
  }
 ]
}